# Generated by Django 5.0.2 on 2024-03-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dorsal', models.CharField(max_length=3)),
                ('posicion', models.CharField(max_length=20)),
                ('estatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreE', models.CharField(max_length=50)),
                ('estadio', models.CharField(max_length=30)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taller.jugador')),
            ],
        ),
    ]
